"""empty message

Revision ID: 191de619b496
Revises: 5fa45584b771
Create Date: 2022-02-20 08:19:16.536771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191de619b496'
down_revision = '5fa45584b771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats_room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_room')
    # ### end Alembic commands ###
