"""empty message

Revision ID: 4cde1b36ee87
Revises: f58e0da4c99d
Create Date: 2022-02-20 17:31:10.903554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde1b36ee87'
down_revision = 'f58e0da4c99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rozbory', sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rozbory', 'saved_at')
    # ### end Alembic commands ###
